import pygame


INIT_EVENT = pygame.USEREVENT + 1
END_INIT_EVENT = pygame.USEREVENT + 2
MAX_GAME_EVENT = pygame.USEREVENT + 3
STOP_GAME = pygame.USEREVENT + 4
TIME_UP = pygame.USEREVENT + 5
SECOND_PASSED = pygame.USEREVENT + 6
STOP_WAIT = pygame.USEREVENT + 7
START_RECORDING = pygame.USEREVENT + 8
STOP_RECORDING = pygame.USEREVENT + 9

RH_PRESS_EVENT = pygame.USEREVENT + 10
RH_RELAX_EVENT = pygame.USEREVENT + 11

RE_NEW_BALL_EVENT = pygame.USEREVENT + 20
RE_DELETE_EVENT = pygame.USEREVENT + 21
